-- MySQL IP Address lookup table.
-- Allows for ip lookup through id number or specified name (if assigned).

DROP TABLE ip;

-- id is autogenerated, name is optional.
CREATE TABLE ip(
	id		INT			 	PRIMARY KEY AUTO_INCREMENT,
	name	VARCHAR(255)	UNIQUE NULL,
	address VARCHAR(255) 	NOT NULL
);